import 'package:flutter/material.dart';
const kDirColor=Color(0xFFFFFDE7);
const kMainColor=Color(0xFFBDBDBD);
const kInputColor=Color(0xFFFFE0B2);
const cFoodName='foodName';
const cFoodType='foodType';
const cFoodPrice='foodPrice';
const cFoodInfo='foodInfo';
const cFoodImg='foodImg';
const cFoodMix='Menu';
const cFoodStarter = 'mStarter';
const cfoodQuan = 'foodquantity';
const cFoodMain='mMain';
const cFoodDesert = 'mDesert';
const cFoodDrinks = 'mDrink';
const cOrders = 'Orders';
const cOrderInfo= 'OrderInfo';
const cTotalBill= 'TotalBill';
const cTableNum = 'TableNumber';
const cUserInfo='userInfo';
const cUserName= 'userName';
const cUserAge= 'userAge';
const cUserEmail = 'userEmail';

